interface Product {
  id: number
  name: string
  description: string
  price: number
  originalPrice?: number
  image: string
  rating: number
  sale?: boolean
  category: string
}

const categories = ["Rings", "Necklaces", "Earrings", "Bracelets", "Pendants", "Watches"]

const productNames = [
  "Eternal Promise Ring",
  "Golden Sunset Necklace",
  "Emerald Drop Earrings",
  "Heritage Chain Bracelet",
  "Starlight Tennis Ring",
  "Celestial Layer Set",
  "Diamond Solitaire Ring",
  "Pearl Strand Necklace",
  "Ruby Stud Earrings",
  "Vintage Gold Bracelet",
  "Sapphire Halo Ring",
  "Crystal Pendant Necklace",
  "Silver Hoop Earrings",
  "Charm Bracelet Set",
  "Rose Gold Band",
  "Moonstone Necklace",
  "Diamond Cluster Earrings",
  "Tennis Bracelet",
  "Engagement Ring",
  "Statement Necklace",
  "Chandelier Earrings",
  "Cuff Bracelet",
  "Wedding Band",
  "Choker Necklace",
  "Stud Earrings",
  "Link Bracelet",
  "Cocktail Ring",
  "Lariat Necklace",
  "Drop Earrings",
  "Bangle Set",
  "Eternity Ring",
  "Chain Necklace",
  "Huggie Earrings",
  "Wrap Bracelet",
  "Signet Ring",
  "Collar Necklace",
  "Threader Earrings",
  "Beaded Bracelet",
  "Stack Ring",
  "Pendant Set",
  "Ear Climbers",
  "Mesh Bracelet",
  "Pinky Ring",
  "Layered Necklace",
  "Statement Earrings",
  "Charm Bracelet",
  "Promise Ring",
  "Opera Necklace",
]

const descriptions = [
  "Handcrafted with precision and attention to detail",
  "Featuring premium materials and expert craftsmanship",
  "A timeless piece perfect for any occasion",
  "Elegant design with contemporary styling",
  "Classic beauty meets modern sophistication",
  "Luxurious finish with exceptional quality",
  "Artisan-made with traditional techniques",
  "Stunning centerpiece for your collection",
  "Versatile design suitable for daily wear",
  "Exquisite detailing and superior materials",
  "Perfect gift for someone special",
  "Sophisticated elegance in every detail",
  "Masterfully crafted for lasting beauty",
  "Unique design with artistic flair",
  "Premium quality with lifetime warranty",
]

const imageQueries = [
  "luxury diamond ring jewelry photography",
  "elegant gold necklace pendant",
  "emerald earrings luxury jewelry",
  "gold bracelet luxury jewelry",
  "pearl necklace luxury jewelry",
  "ruby ring luxury jewelry",
  "sapphire earrings luxury jewelry",
  "silver bracelet luxury jewelry",
  "diamond pendant necklace",
  "gold wedding band ring",
  "crystal earrings luxury jewelry",
  "vintage gold bracelet",
  "platinum ring luxury jewelry",
  "pearl earrings luxury jewelry",
  "gold chain necklace luxury",
]

export function generateProducts(count: number): Product[] {
  const products: Product[] = []

  for (let i = 1; i <= count; i++) {
    const category = categories[Math.floor(Math.random() * categories.length)]
    const baseName = productNames[Math.floor(Math.random() * productNames.length)]
    const description = descriptions[Math.floor(Math.random() * descriptions.length)]
    const imageQuery = imageQueries[Math.floor(Math.random() * imageQueries.length)]

    const basePrice = Math.floor(Math.random() * 2000) + 200 // $200 - $2200
    const isSale = Math.random() < 0.3 // 30% chance of sale
    const originalPrice = isSale ? basePrice + Math.floor(Math.random() * 500) + 100 : undefined
    const rating = Math.floor(Math.random() * 2) + 4 // 4-5 stars

    products.push({
      id: i,
      name: `${baseName} ${i}`,
      description: description,
      price: basePrice,
      originalPrice: originalPrice,
      image: "", // Removed placeholder.svg
      rating: rating,
      sale: isSale,
      category: category,
    })
  }

  return products
}

// Real product catalog from user data
export const realProducts: Product[] = [
  { id: 1, image: "/images/AJPE1.jpg", category: "Earrings", price: 8.4, description: "Product SKU AJPE1", name: "AJPE1 Earrings", rating: 4.1 },
  { id: 2, image: "/images/AJPE2.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE2", name: "AJPE2 Earrings", rating: 4.1 },
  { id: 3, image: "/images/AJPE3.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE3", name: "AJPE3 Earrings", rating: 3.8 },
  { id: 4, image: "/images/AJPE4.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE4", name: "AJPE4 Earrings", rating: 4.8 },
  { id: 5, image: "/images/AJPE5.jpg", category: "Earrings", price: 10.2, description: "Product SKU AJPE5", name: "AJPE5 Earrings", rating: 3.5 },
  { id: 6, image: "/images/AJPE6.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE6", name: "AJPE6 Earrings", rating: 4.0 },
  { id: 7, image: "/images/AJPE7.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE7", name: "AJPE7 Earrings", rating: 3.7 },
  { id: 8, image: "/images/AJPE8.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE8", name: "AJPE8 Earrings", rating: 4.6 },
  { id: 9, image: "/images/AJPE9.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE9", name: "AJPE9 Earrings", rating: 4.5 },
  { id: 10, image: "/images/AJPE10.jpg", category: "Earrings", price: 10.2, description: "Product SKU AJPE10", name: "AJPE10 Earrings", rating: 3.8 },
  { id: 11, image: "/images/AJPE11.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE11", name: "AJPE11 Earrings", rating: 4.6 },
  { id: 12, image: "/images/AJPE12.jpg", category: "Earrings", price: 10.2, description: "Product SKU AJPE12", name: "AJPE12 Earrings", rating: 4.9 },
  { id: 13, image: "/images/AJPE13.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE13", name: "AJPE13 Earrings", rating: 4.8 },
  { id: 14, image: "/images/AJPE14.jpg", category: "Earrings", price: 10.2, description: "Product SKU AJPE14", name: "AJPE14 Earrings", rating: 4.7 },
  { id: 15, image: "/images/AJPE15.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE15", name: "AJPE15 Earrings", rating: 4.4 },
  { id: 16, image: "/images/AJPE16.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE16", name: "AJPE16 Earrings", rating: 4.8 },
  { id: 17, image: "/images/AJPE17.jpg", category: "Earrings", price: 8.4, description: "Product SKU AJPE17", name: "AJPE17 Earrings", rating: 4.2 },
  { id: 18, image: "/images/AJPE18.jpg", category: "Earrings", price: 9.9, description: "Product SKU AJPE18", name: "AJPE18 Earrings", rating: 3.6 },
  { id: 19, image: "/images/AJPE19.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE19", name: "AJPE19 Earrings", rating: 3.8 },
  { id: 20, image: "/images/AJPE20.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE20", name: "AJPE20 Earrings", rating: 3.9 },
  { id: 21, image: "/images/AJPE21.jpg", category: "Earrings", price: 10.2, description: "Product SKU AJPE21", name: "AJPE21 Earrings", rating: 4.3 },
  { id: 22, image: "/images/AJPE22.jpg", category: "Earrings", price: 8.4, description: "Product SKU AJPE22", name: "AJPE22 Earrings", rating: 4.7 },
  { id: 23, image: "/images/AJPE23.jpg", category: "Earrings", price: 13.8, description: "Product SKU AJPE23", name: "AJPE23 Earrings", rating: 3.8 },
  { id: 24, image: "/images/AJPE24.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE24", name: "AJPE24 Earrings", rating: 4.6 },
  { id: 25, image: "/images/AJPE25.jpg", category: "Earrings", price: 11.4, description: "Product SKU AJPE25", name: "AJPE25 Earrings", rating: 3.9 },
  { id: 26, image: "/images/AJPE26.jpg", category: "Earrings", price: 9.6, description: "Product SKU AJPE26", name: "AJPE26 Earrings", rating: 4.3 },
  { id: 27, image: "/images/AJPE27.jpg", category: "Earrings", price: 9.6, description: "Product SKU AJPE27", name: "AJPE27 Earrings", rating: 4.7 },
  { id: 28, image: "/images/AJPE28.jpg", category: "Earrings", price: 10.2, description: "Product SKU AJPE28", name: "AJPE28 Earrings", rating: 4.8 },
  { id: 29, image: "/images/AJPE29.jpg", category: "Earrings", price: 8.4, description: "Product SKU AJPE29", name: "AJPE29 Earrings", rating: 3.5 },
  { id: 30, image: "/images/AJPE30.jpg", category: "Earrings", price: 8.4, description: "Product SKU AJPE30", name: "AJPE30 Earrings", rating: 4.6 },
  { id: 31, image: "/images/AJPE31.jpg", category: "Earrings", price: 11.4, description: "Product SKU AJPE31", name: "AJPE31 Earrings", rating: 4.6 },
  { id: 32, image: "/images/AJPE32.jpg", category: "Earrings", price: 7.5, description: "Product SKU AJPE32", name: "AJPE32 Earrings", rating: 4.3 },
  { id: 33, image: "/images/AJPE33.jpg", category: "Earrings", price: 11.4, description: "Product SKU AJPE33", name: "AJPE33 Earrings", rating: 4.9 },
  { id: 34, image: "/images/AJPE34.jpg", category: "Earrings", price: 8.7, description: "Product SKU AJPE34", name: "AJPE34 Earrings", rating: 3.5 },
  { id: 35, image: "/images/AJPE35.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE35", name: "AJPE35 Earrings", rating: 3.9 },
  { id: 36, image: "/images/AJPE36.jpg", category: "Earrings", price: 9.6, description: "Product SKU AJPE36", name: "AJPE36 Earrings", rating: 4.2 },
  { id: 37, image: "/images/AJPE37.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE37", name: "AJPE37 Earrings", rating: 3.6 },
  { id: 38, image: "/images/AJPE38.jpg", category: "Earrings", price: 10.2, description: "Product SKU AJPE38", name: "AJPE38 Earrings", rating: 4.4 },
  { id: 39, image: "/images/AJPE39.jpg", category: "Earrings", price: 8.4, description: "Product SKU AJPE39", name: "AJPE39 Earrings", rating: 4.8 },
  { id: 40, image: "/images/AJPE40.jpg", category: "Earrings", price: 10.2, description: "Product SKU AJPE40", name: "AJPE40 Earrings", rating: 4.5 },
  { id: 41, image: "/images/AJPE41.jpg", category: "Earrings", price: 10.2, description: "Product SKU AJPE41", name: "AJPE41 Earrings", rating: 4.5 },
  { id: 42, image: "/images/AJPE42.jpg", category: "Earrings", price: 6.36, description: "Product SKU AJPE42", name: "AJPE42 Earrings", rating: 5.0 },
  { id: 43, image: "/images/AJPE43.jpg", category: "Earrings", price: 9.0, description: "Product SKU AJPE43", name: "AJPE43 Earrings", rating: 3.7 },
  { id: 44, image: "/images/AJPE44.jpg", category: "Earrings", price: 8.4, description: "Product SKU AJPE44", name: "AJPE44 Earrings", rating: 4.1 },
  { id: 45, image: "/images/AJPE45.jpg", category: "Earrings", price: 7.2, description: "Product SKU AJPE45", name: "AJPE45 Earrings", rating: 4.6 },
  { id: 46, image: "/images/AJPE46.jpg", category: "Earrings", price: 8.4, description: "Product SKU AJPE46", name: "AJPE46 Earrings", rating: 4.2 },
  { id: 47, image: "/images/AJPE47.jpg", category: "Earrings", price: 10.8, description: "Product SKU AJPE47", name: "AJPE47 Earrings", rating: 4.1 },
  { id: 48, image: "/images/AJPS1.jpg", category: "Studs", price: 9.0, description: "Product SKU AJPS1", name: "AJPS1 Studs", rating: 4.7 },
  { id: 49, image: "/images/AJPN1.jpg", category: "Necklace", price: 10.8, description: "Product SKU AJPN1", name: "AJPN1 Necklace", rating: 4.8 },
  { id: 50, image: "/images/AJPN2.jpg", category: "Necklace", price: 9.0, description: "Product SKU AJPN2", name: "AJPN2 Necklace", rating: 5.0 },
  { id: 51, image: "/images/AJPN3.jpg", category: "Necklace", price: 8.4, description: "Product SKU AJPN3", name: "AJPN3 Necklace", rating: 4.4 },
  { id: 52, image: "/images/AJPN4.jpg", category: "Necklace", price: 9.0, description: "Product SKU AJPN4", name: "AJPN4 Necklace", rating: 4.4 },
  { id: 53, image: "/images/AJPN6.jpg", category: "Necklace", price: 10.8, description: "Product SKU AJPN6", name: "AJPN6 Necklace", rating: 4.2 },
  { id: 54, image: "/images/AJPN7.jpg", category: "Necklace", price: 9.0, description: "Product SKU AJPN7", name: "AJPN7 Necklace", rating: 4.9 },
  { id: 55, image: "/images/AJPN8.jpg", category: "Necklace", price: 9.0, description: "Product SKU AJPN8", name: "AJPN8 Necklace", rating: 3.9 },
  { id: 56, image: "/images/AJPN9.jpg", category: "Necklace", price: 10.8, description: "Product SKU AJPN9", name: "AJPN9 Necklace", rating: 3.7 },
  { id: 57, image: "/images/AJPN10.jpg", category: "Necklace", price: 11.4, description: "Product SKU AJPN10", name: "AJPN10 Necklace", rating: 4.9 },
  { id: 58, image: "/images/AJPN11.jpg", category: "Necklace", price: 9.6, description: "Product SKU AJPN11", name: "AJPN11 Necklace", rating: 4.0 },
  { id: 59, image: "/images/AJPN12.jpg", category: "Necklace", price: 9.6, description: "Product SKU AJPN12", name: "AJPN12 Necklace", rating: 3.8 },
  { id: 60, image: "/images/AJPN13.jpg", category: "Necklace", price: 9.6, description: "Product SKU AJPN13", name: "AJPN13 Necklace", rating: 4.7 },
  { id: 61, image: "/images/AJPN14.jpg", category: "Necklace", price: 8.7, description: "Product SKU AJPN14", name: "AJPN14 Necklace", rating: 3.6 },
  { id: 62, image: "/images/AJPN15.jpg", category: "Necklace", price: 7.2, description: "Product SKU AJPN15", name: "AJPN15 Necklace", rating: 4.2 },
  { id: 63, image: "/images/AJPN16.jpg", category: "Necklace", price: 10.2, description: "Product SKU AJPN16", name: "AJPN16 Necklace", rating: 3.7 },
  { id: 64, image: "/images/AJPN17.jpg", category: "Necklace", price: 9.0, description: "Product SKU AJPN17", name: "AJPN17 Necklace", rating: 4.4 },
  { id: 65, image: "/images/AJPN18.jpg", category: "Necklace", price: 15.0, description: "Product SKU AJPN18", name: "AJPN18 Necklace", rating: 4.1 },
  { id: 66, image: "/images/AJPN19.jpg", category: "Necklace", price: 6.9, description: "Product SKU AJPN19", name: "AJPN19 Necklace", rating: 4.1 },
  { id: 67, image: "/images/AJPN20.jpg", category: "Necklace", price: 9.0, description: "Product SKU AJPN20", name: "AJPN20 Necklace", rating: 4.1 },
  { id: 68, image: "/images/AJPN21.jpg", category: "Necklace", price: 9.0, description: "Product SKU AJPN21", name: "AJPN21 Necklace", rating: 3.5 },
  { id: 69, image: "/images/AJPR1.jpg", category: "Ring", price: 9.6, description: "Product SKU AJPR1", name: "AJPR1 Ring", rating: 3.6 },
  { id: 70, image: "/images/AJPR2.jpg", category: "Ring", price: 7.5, description: "Product SKU AJPR2", name: "AJPR2 Ring", rating: 4.9 },
  { id: 71, image: "/images/AJPR3.jpg", category: "Ring", price: 8.4, description: "Product SKU AJPR3", name: "AJPR3 Ring", rating: 4.1 },
  { id: 72, image: "/images/AJPR4.jpg", category: "Ring", price: 7.2, description: "Product SKU AJPR4", name: "AJPR4 Ring", rating: 4.3 },
  { id: 73, image: "/images/AJPR5.jpg", category: "Ring", price: 9.3, description: "Product SKU AJPR5", name: "AJPR5 Ring", rating: 4.9 },
  { id: 74, image: "/images/AJPR6.jpg", category: "Ring", price: 9.3, description: "Product SKU AJPR6", name: "AJPR6 Ring", rating: 4.5 },
  { id: 75, image: "/images/AJPR7.jpg", category: "Ring", price: 6.6, description: "Product SKU AJPR7", name: "AJPR7 Ring", rating: 4.4 },
  { id: 76, image: "/images/AJPR8.jpg", category: "Ring", price: 7.2, description: "Product SKU AJPR8", name: "AJPR8 Ring", rating: 4.7 },
  { id: 77, image: "/images/AJPR9.jpg", category: "Ring", price: 9.0, description: "Product SKU AJPR9", name: "AJPR9 Ring", rating: 4.0 },
  { id: 78, image: "/images/AJPR10.jpg", category: "Ring", price: 8.4, description: "Product SKU AJPR10", name: "AJPR10 Ring", rating: 4.1 },
  { id: 79, image: "/images/AJPR11.jpg", category: "Ring", price: 8.4, description: "Product SKU AJPR11", name: "AJPR11 Ring", rating: 4.3 },
  { id: 80, image: "/images/AJPR12.jpg", category: "Bracelet", price: 13.2, description: "Product SKU AJPR12", name: "AJPR12 Bracelet", rating: 3.8 },
  { id: 81, image: "/images/AJPR13.jpg", category: "Bracelet", price: 8.7, description: "Product SKU AJPR13", name: "AJPR13 Bracelet", rating: 4.3 },
  { id: 82, image: "/images/AJKR1.jpg", category: "Ring", price: 10.8, description: "Product SKU AJKR1", name: "AJKR1 Ring", rating: 4.3 },
  { id: 83, image: "/images/AJKR2.jpg", category: "Ring", price: 12.0, description: "Product SKU AJKR2", name: "AJKR2 Ring", rating: 4.1 },
  { id: 84, image: "/images/AJKS1.jpg", category: "Studs", price: 14.4, description: "Product SKU AJKS1", name: "AJKS1 Studs", rating: 4.0 },
  { id: 85, image: "/images/AJKS2.jpg", category: "Studs", price: 12.6, description: "Product SKU AJKS2", name: "AJKS2 Studs", rating: 3.6 },
  { id: 86, image: "/images/AJKS3.jpg", category: "Studs", price: 11.4, description: "Product SKU AJKS3", name: "AJKS3 Studs", rating: 4.1 },
  { id: 87, image: "/images/AJKS4.jpg", category: "Studs", price: 12.6, description: "Product SKU AJKS4", name: "AJKS4 Studs", rating: 4.9 },
  { id: 88, image: "/images/AJPR12.jpg", category: "Ring", price: 13.2, description: "Product SKU AJPR12", name: "AJPR12 Ring", rating: 3.6 },
  { id: 89, image: "/images/AJPR13.jpg", category: "Bracelet", price: 8.7, description: "Product SKU AJPR13", name: "AJPR13 Bracelet", rating: 4.8 },
  { id: 90, image: "/images/AJKR1.jpg", category: "Ring", price: 10.8, description: "Product SKU AJKR1", name: "AJKR1 Ring", rating: 4.3 },
  { id: 91, image: "/images/AJKR2.jpg", category: "Ring", price: 12, description: "Product SKU AJKR2", name: "AJKR2 Ring", rating: 4.3 },
  { id: 92, image: "/images/AJKS1.jpg", category: "Studs", price: 14.4, description: "Product SKU AJKS1", name: "AJKS1 Studs", rating: 3.9 },
  { id: 93, image: "/images/AJKS2.jpg", category: "Studs", price: 12.6, description: "Product SKU AJKS2", name: "AJKS2 Studs", rating: 3.7 },
  { id: 94, image: "/images/AJKS3.jpg", category: "Studs", price: 11.4, description: "Product SKU AJKS3", name: "AJKS3 Studs", rating: 4.3 },
  { id: 95, image: "/images/AJKS4.jpg", category: "Studs", price: 12.6, description: "Product SKU AJKS4", name: "AJKS4 Studs", rating: 3.8 },
  { id: 96, image: "/images/AJKE1.jpg", category: "Earrings", price: 16.2, description: "Product SKU AJKE1", name: "AJKE1 Earrings", rating: 3.9 },
  { id: 97, image: "/images/AJKE2.jpg", category: "Earrings", price: 13.8, description: "Product SKU AJKE2", name: "AJKE2 Earrings", rating: 3.5 },
  { id: 98, image: "/images/AJKE3.jpg", category: "Earrings", price: 17.4, description: "Product SKU AJKE3", name: "AJKE3 Earrings", rating: 4.0 },
  { id: 99, image: "/images/AJKE4.jpg", category: "Earrings", price: 15, description: "Product SKU AJKE4", name: "AJKE4 Earrings", rating: 4.2 },
  { id: 100, image: "/images/AJKE5.jpg", category: "Earrings", price: 16.8, description: "Product SKU AJKE5", name: "AJKE5 Earrings", rating: 3.6 },
  { id: 101, image: "/images/AJKE6.jpg", category: "Earrings", price: 15.6, description: "Product SKU AJKE6", name: "AJKE6 Earrings", rating: 4.8 },
  { id: 102, image: "/images/AJKE7.jpg", category: "Earrings", price: 15, description: "Product SKU AJKE7", name: "AJKE7 Earrings", rating: 4.4 },
  { id: 103, image: "/images/AJKE8.jpg", category: "Earrings", price: 15.6, description: "Product SKU AJKE8", name: "AJKE8 Earrings", rating: 4.4 },
  { id: 104, image: "/images/AJKE9.jpg", category: "Earcuff", price: 15, description: "Product SKU AJKE9", name: "AJKE9 Earcuff", rating: 4.4 },
  { id: 105, image: "/images/AJKE10.jpg", category: "Earrings", price: 12.6, description: "Product SKU AJKE10", name: "AJKE10 Earrings", rating: 4.8 },
  { id: 106, image: "/images/AJ.jpg", category: "Earrings", price: 13.8, description: "Product SKU AJKE11", name: "AJKE11 Earrings", rating: 3.7 },
  { id: 107, image: "/images/AJKE12.jpg", category: "Earrings", price: 13.8, description: "Product SKU AJKE12", name: "AJKE12 Earrings", rating: 3.7 },
  { id: 108, image: "/images/AJKE13.jpg", category: "Earrings", price: 12.6, description: "Product SKU AJKE13", name: "AJKE13 Earrings", rating: 4.1 },
  { id: 109, image: "/images/AJKE14.jpg", category: "Earrings", price: 13.8, description: "Product SKU AJKE14", name: "AJKE14 Earrings", rating: 4.2 },
  { id: 110, image: "/images/AJKE15.jpg", category: "Earrings", price: 16.2, description: "Product SKU AJKE15", name: "AJKE15 Earrings", rating: 4.8 },
  { id: 111, image: "/images/AJKE16.jpg", category: "Earrings", price: 15.6, description: "Product SKU AJKE16", name: "AJKE16 Earrings", rating: 4.8 },
  { id: 112, image: "/images/AJKE17.jpg", category: "Earrings", price: 16.8, description: "Product SKU AJKE17", name: "AJKE17 Earrings", rating: 4.5 },
  { id: 113, image: "/images/AJKE18.jpg", category: "Earrings", price: 17.4, description: "Product SKU AJKE18", name: "AJKE18 Earrings", rating: 4.8 },
  { id: 114, image: "/images/AJKE19.jpg", category: "Earrings", price: 11.4, description: "Product SKU AJKE19", name: "AJKE19 Earrings", rating: 4.8 },
  { id: 115, image: "/images/AJKE20.jpg", category: "Earrings", price: 13.8, description: "Product SKU AJKE20", name: "AJKE20 Earrings", rating: 5.0 },
  { id: 116, image: "/images/AJKE21.jpg", category: "Earrings", price: 15.6, description: "Product SKU AJKE21", name: "AJKE21 Earrings", rating: 4.3 },
  { id: 117, image: "/images/AJKE22.jpg", category: "Earrings", price: 15.6, description: "Product SKU AJKE22", name: "AJKE22 Earrings", rating: 3.5 },
  { id: 118, image: "/images/AJKE23.jpg", category: "Earrings", price: 12, description: "Product SKU AJKE23", name: "AJKE23 Earrings", rating: 3.7 },
  { id: 119, image: "/images/AJKE24.jpg", category: "Earrings", price: 13.2, description: "Product SKU AJKE24", name: "AJKE24 Earrings", rating: 5.0 },
  { id: 120, image: "/images/AJKE25.jpg", category: "Earrings", price: 14.4, description: "Product SKU AJKE25", name: "AJKE25 Earrings", rating: 3.6 },
  { id: 121, image: "/images/AJKE26.jpg", category: "Earrings", price: 13.2, description: "Product SKU AJKE26", name: "AJKE26 Earrings", rating: 4.8 },
  { id: 122, image: "/images/AJKE27.jpg", category: "Earrings", price: 13.8, description: "Product SKU AJKE27", name: "AJKE27 Earrings", rating: 4.8 },
  { id: 123, image: "/images/AJKE28.jpg", category: "Earrings", price: 13.8, description: "Product SKU AJKE28", name: "AJKE28 Earrings", rating: 3.8 },
  { id: 124, image: "/images/AJKE29.jpg", category: "Earrings", price: 13.2, description: "Product SKU AJKE29", name: "AJKE29 Earrings", rating: 4.4 },
  { id: 125, image: "/images/AJKE30.jpg", category: "Earrings", price: 11.4, description: "Product SKU AJKE30", name: "AJKE30 Earrings", rating: 3.9 },
  { id: 126, image: "/images/AJKE31.jpg", category: "Earrings", price: 14.4, description: "Product SKU AJKE31", name: "AJKE31 Earrings", rating: 4.0 },
  { id: 127, image: "/images/AJKE32.jpg", category: "Earrings", price: 14.4, description: "Product SKU AJKE32", name: "AJKE32 Earrings", rating: 4.4 },
  { id: 128, image: "/images/AJKE33.jpg", category: "Earrings", price: 17.4, description: "Product SKU AJKE33", name: "AJKE33 Earrings", rating: 4.0 },
  { id: 129, image: "/images/AJKN1.jpg", category: "Necklace", price: 10.8, description: "Product SKU AJKN1", name: "AJKN1 Necklace", rating: 4.1 },
  { id: 130, image: "/images/AJKN2.jpg", category: "Necklace", price: 10.8, description: "Product SKU AJKN2", name: "AJKN2 Necklace", rating: 4.1 },
  { id: 131, image: "/images/AJKN3.jpg", category: "Necklace", price: 10.8, description: "Product SKU AJKN3", name: "AJKN3 Necklace", rating: 4.1 },
  { id: 132, image: "/images/AJKN4.jpg", category: "Necklace", price: 10.8, description: "Product SKU AJKN4", name: "AJKN4 Necklace", rating: 4.8 },
  { id: 133, image: "/images/AJKN5.jpg", category: "Necklace", price: 10.8, description: "Product SKU AJKN5", name: "AJKN5 Necklace", rating: 4.7 },
  { id: 134, image: "/images/AJKN6.jpg", category: "Necklace", price: 15, description: "Product SKU AJKN6", name: "AJKN6 Necklace", rating: 4.4 },
  { id: 135, image: "/images/AJKN7.jpg", category: "Necklace", price: 18, description: "Product SKU AJKN7", name: "AJKN7 Necklace", rating: 4.3 },
  { id: 136, image: "/images/AJKN8.jpg", category: "Necklace", price: 20.4, description: "Product SKU AJKN8", name: "AJKN8 Necklace", rating: 3.7 },
  { id: 137, image: "/images/AJKN9.jpg", category: "Necklace", price: 22.2, description: "Product SKU AJKN9", name: "AJKN9 Necklace", rating: 3.7 },
  { id: 138, image: "/images/AJKN10.jpg", category: "Necklace", price: 22.2, description: "Product SKU AJKN10", name: "AJKN10 Necklace", rating: 3.5 },
  { id: 139, image: "/images/AJKN11.jpg", category: "Necklace", price: 19.2, description: "Product SKU AJKN11", name: "AJKN11 Necklace", rating: 4.2 },
  { id: 140, image: "/images/AJKN12.jpg", category: "Necklace", price: 14.4, description: "Product SKU AJKN12", name: "AJKN12 Necklace", rating: 4.4 },
  { id: 141, image: "/images/AJKN13.jpg", category: "Necklace", price: 14.4, description: "Product SKU AJKN13", name: "AJKN13 Necklace", rating: 5.0 },
  { id: 142, image: "/images/AJKN14.jpg", category: "Necklace", price: 25.2, description: "Product SKU AJKN14", name: "AJKN14 Necklace", rating: 3.9 },
  { id: 143, image: "/images/AJKN15.jpg", category: "Necklace", price: 22.8, description: "Product SKU AJKN15", name: "AJKN15 Necklace", rating: 3.6 },
  { id: 144, image: "/images/AJKN16.jpg", category: "Necklace", price: 13.2, description: "Product SKU AJKN16", name: "AJKN16 Necklace", rating: 4.0 },
  { id: 145, image: "/images/AJKN17.jpg", category: "Necklace", price: 13.2, description: "Product SKU AJKN17", name: "AJKN17 Necklace", rating: 3.7 },
  { id: 146, image: "/images/AJKN18.jpg", category: "Necklace", price: 11.4, description: "Product SKU AJKN18", name: "AJKN18 Necklace", rating: 3.9 },
  { id: 147, image: "/images/AJKN19.jpg", category: "Necklace", price: 10.8, description: "Product SKU AJKN19", name: "AJKN19 Necklace", rating: 4.1 },
  { id: 148, image: "/images/AJKN20.jpg", category: "Necklace", price: 10.8, description: "Product SKU AJKN20", name: "AJKN20 Necklace", rating: 4.9 },
  { id: 149, image: "/images/AJKN21.jpg", category: "Necklace", price: 13.8, description: "Product SKU AJKN21", name: "AJKN21 Necklace", rating: 3.9 },
  { id: 150, image: "/images/AJKN22.jpg", category: "Necklace", price: 13.2, description: "Product SKU AJKN22", name: "AJKN22 Necklace", rating: 3.5 },
  { id: 151, image: "/images/AJKB1..jpg", category: "Bracelet", price: 15.6, description: "Product SKU AJKB1", name: "AJKB1 Bracelet", rating: 4.1 },
  { id: 152, image: "/images/AJKB2..jpg", category: "Bracelet", price: 19.2, description: "Product SKU AJKB2", name: "AJKB2 Bracelet", rating: 3.6 },
  { id: 153, image: "/images/AJKB3..jpg", category: "Bracelet", price: 13.2, description: "Product SKU AJKB3", name: "AJKB3 Bracelet", rating: 4.6 },
  { id: 154, image: "/images/AJKB4..jpg", category: "Bracelet", price: 15.6, description: "Product SKU AJKB4", name: "AJKB4 Bracelet", rating: 3.8 },
  { id: 155, image: "/images/AJKB5..jpg", category: "Bracelet", price: 16.8, description: "Product SKU AJKB5", name: "AJKB5 Bracelet", rating: 3.8 },
  { id: 156, image: "/images/AJKB6.jpg", category: "Bracelet", price: 18, description: "Product SKU AJKB6", name: "AJKB6 Bracelet", rating: 4.3 },
  { id: 157, image: "/images/AJKB7..jpg", category: "Bracelet", price: 16.8, description: "Product SKU AJKB7", name: "AJKB7 Bracelet", rating: 4.9 },
  { id: 158, image: "/images/AJKB8.jpg", category: "Bracelet", price: 20.4, description: "Product SKU AJKB8", name: "AJKB8 Bracelet", rating: 3.7 },
];
  